### ISSUE TITLE
RoundState serializing error

### ISSUE THREAD

**Issue by AlexisKv** [turbolay/WasabiMonitor#3]
I have rpc endpoint. 

        
	 [JsonRpcMethod("get-rounds")]
	public static List<RoundState> GetRounds(string? startTime = null, string? endTime = null)
	{
		var (startDateTime, endDateTime) = ParseInterval(startTime, endTime);
		return Analyzer.GetRoundsInInterval(startDateTime, endDateTime);
	}
	
Get-rounds has returning list of RoundState objects. When it's serializing this object, I receive this error:

> "Error getting value from 'Address' on 'System.Net.IPAddress'.

Fun fact is that I don't have any IPAddress or Adress object into my RoundState.
With another endpoint, which is returning another object **I don't have** theese problems.

This RoundState  object is copied from WasabiWallet. And this is more detailed exception:
> Newtonsoft.Json.JsonSerializationException: Error getting value from 'Address' on 'System.Net.IPAddress'. ---> System.Net.Sockets.SocketException (10045): The attempted operation is not supported for the type of object referenced. at System.Net.IPAddress.get_Address() at lambda_method127(Closure, Object) at Newtonsoft.Json.Serialization.ExpressionValueProvider.GetValue(Object target) --- End of inner exception stack trace --- at Newtonsoft.Json.Serialization.ExpressionValueProvider.GetValue(Object target) at

**Comment by turbolay** [comment]
Fixed in #1
